on:
  workflow_dispatch:  # Manuelle Ausführung erlauben
  schedule:
    - cron: "8 * * * *"  # Optional: auch geplante Ausführung

jobs:
  update-catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove existing catalog (if needed)
        run: rm -rf catalog

      - name: Run sync script
        run: python3 sync.py

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update catalog, database and images" || echo "No changes to commit"

      - name: Push changes
        run: git push
