on:
  workflow_dispatch:        # Manuelle Ausführung möglich
  schedule:
    - cron: "8 * * * *"     # Optionale zeitgesteuerte Ausführung

jobs:
  update-catalog:
    runs-on: ubuntu-latest
    env:
      GIT_HTTP_TIMEOUT: 600
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove existing catalog, images and DB (if needed)
        run: |
          rm -rf catalog Images cards.db

      - name: Run sync script
        run: python3 sync.py

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git config --global http.postBuffer 1073741824  # 1GB
          git config --global core.compression 9
          git config --global http.version HTTP/1.1

      - name: Commit non-image changes (catalog and DB)
        run: |
          git add catalog cards.db
          git commit -m "Update catalog and database" || echo "No non-image changes to commit"
          git push

      - name: Commit and push images per language
        run: |
          for lang in de en fr it; do
            echo "Processing language: $lang"
            git add Images/$lang
            git commit -m "Update images for $lang" || echo "No changes for $lang"
            git push
          done
