name: Sync Glimmer Data

on:
  workflow_dispatch:
  schedule:
    - cron: "38 * * * *"  # Jede Stunde zur Minute 38

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      GIT_HTTP_TIMEOUT: 600
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Remove existing data in glimmer folder
        run: |
          rm -rf glimmer/catalog glimmer/Thumbnails glimmer/cards_database.sqlite glimmer/cards_database_original_Scheme.sqlite

      - name: Run sync script
        env:
          LORCANA_SECRET_TOKEN: ${{ secrets.LORCANA_SECRET_TOKEN }}
        run: python3 glimmer/syncGlimmer.py

      - name: Run DB converter
        run: python3 glimmer/convert_db.py

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git config --global http.postBuffer 1073741824

      - name: Commit and push changes in glimmer folder
        run: |
          git reset --hard
          git pull --rebase
          git add glimmer/catalog glimmer/Thumbnails
          git add -f glimmer/cards_database.sqlite glimmer/cards_database_original_Scheme.sqlite
          git commit -m "Update Glimmer data" || echo "No changes to commit"
          git push origin main
