name: Publish Glimmer.Scan-Compatible Build

on:
  workflow_dispatch:
  schedule:
    - cron: "38 * * * *"  # Jede Stunde zur Minute 38

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GIT_HTTP_TIMEOUT: 600
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Run sync script
        env:
          LORCANA_SECRET_TOKEN: ${{ secrets.LORCANA_SECRET_TOKEN }}
        run: |
          python3 scripts/syncGlimmer.py

      - name: Run DB converter
        run: python3 scripts/convert_db.py

      - name: Copy DB files to repository root
        run: |
          cp scripts/cards_database_original_Scheme.sqlite .
          cp scripts/cards_database.sqlite .

      - name: Remove any previous output directory
        run: rm -rf output

      - name: Prepare output directory
        run: |
          mkdir output
          cp -r catalog output/
          cp -r Thumbnails output/
          cp cards_database.sqlite output/
          cp cards_database_original_Scheme.sqlite output/

      - name: Publish output to glimmer.scan-compatible branch
        uses: s0/git-publish-subdir-action@develop
        with:
          folder: output
          branch: glimmer.scan-compatible
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "Update catalog, DB and thumbnails: ${{ github.sha }}"
