name: Sync Glimmer.Scan-Compatible

on:
  workflow_dispatch:
  schedule:
    - cron: "38 * * * *"  # Jede Stunde zur Minute 38

jobs:
  update-catalog:
    runs-on: ubuntu-latest
    env:
      GIT_HTTP_TIMEOUT: 600
    steps:
      - name: Checkout glimmer.scan-compatible branch
        uses: actions/checkout@v4
        with:
          ref: glimmer.scan-compatible
          fetch-depth: 0

      - name: Clean glimmer.scan-compatible branch
        run: |
          echo "Cleaning branch..."
          git rm -r --ignore-unmatch .
          git clean -fdx
          git commit -am "Clean branch" || echo "Nothing to clean"
          git push origin glimmer.scan-compatible --force

      - name: Run sync script
        env:
          LORCANA_SECRET_TOKEN: ${{ secrets.LORCANA_SECRET_TOKEN }}
        run: python3 scripts/syncGlimmer.py

      - name: Run DB converter
        run: python3 scripts/convert_db.py

      - name: Commit new files
        run: |
          git add catalog Thumbnails
          git add -f cards_database.sqlite cards_database_original_Scheme.sqlite
          git commit -m "Update catalog, DB and thumbnails" || echo "No changes to commit"
          git push origin glimmer.scan-compatible
