name: Sync Glimmer.Scan-Compatible

on:
  workflow_dispatch:
  schedule:
    - cron: "38 * * * *"  # Jede Stunde zur Minute 38

jobs:
  update-catalog:
    runs-on: ubuntu-latest
    env:
      GIT_HTTP_TIMEOUT: 600
    steps:
      - name: Checkout glimmer.scan-compatible branch
        uses: actions/checkout@v4
        with:
          ref: glimmer.scan-compatible

      - name: Remove existing DB files from repo
        run: |
          # Entferne getrackte DB-Dateien (fehlerfrei, falls nicht vorhanden)
          git rm -f --ignore-unmatch cards_database.sqlite cards_database_original_Scheme.sqlite || true
          # Lösche die Dateien aus dem Dateisystem
          rm -f cards_database.sqlite cards_database_original_Scheme.sqlite

      - name: Remove existing catalog and Thumbnails directories
        run: rm -rf catalog Thumbnails

      - name: Run sync script
        env:
          LORCANA_SECRET_TOKEN: ${{ secrets.LORCANA_SECRET_TOKEN }}
        run: python3 sync.py

      - name: Run DB converter
        run: python3 convert_db.py

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git config --global http.postBuffer 1073741824

      - name: Commit and push changes
        run: |
          git reset --hard
          git pull --rebase
          git add catalog Thumbnails
          git add -f cards_database.sqlite cards_database_original_Scheme.sqlite
          git commit -m "Update catalog, DB and thumbnails" || echo "No changes to commit"
          git push origin glimmer.scan-compatible
