name: Sync Glimmer

on:
  workflow_dispatch:
  schedule:
    - cron: "38 * * * *"  # Jede Stunde zur Minute 38

jobs:
  update-glimmer:
    runs-on: ubuntu-latest
    env:
      GIT_HTTP_TIMEOUT: 600
    steps:
      - name: Checkout Repository (Main Branch)
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Clean glimmer folder
        run: |
          cd glimmer
          echo "Lösche alle Dateien und Ordner außer syncGlimmer.py und convert_db.py ..."
          # Löscht alle Dateien und Ordner im aktuellen Verzeichnis, außer der beiden Scripts
          find . -maxdepth 1 ! -name '.' ! -name 'syncGlimmer.py' ! -name 'convert_db.py' -exec rm -rf {} +
          cd ..
      
      - name: Run sync script
        run: python3 glimmer/syncGlimmer.py
        env:
          LORCANA_SECRET_TOKEN: ${{ secrets.LORCANA_SECRET_TOKEN }}

      - name: Run DB converter
        run: python3 glimmer/convert_db.py

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git config --global http.postBuffer 1073741824

      - name: Commit and push changes
        run: |
          git add glimmer
          git commit -m "Update glimmer: catalog, DB and thumbnails" || echo "No changes to commit"
          git push origin main
